### ISSUE TITLE
Training model on additional data?

### ISSUE THREAD

**Issue by BenRachmiel** [imvladikon/wav2vec2-hebrew#1]
Hey, I've got a quite large dataset that I'd like to finetune the model on. My data is currently organized into a JSON with the following format:

{"audio_filepath": "datapath/Recording #1.wav", "duration": 7.0, "text": "טלפון תשע תשע שלוש שמונה שמונה חמש שבע אפס תשע אפס "}
{"audio_filepath": "datapath/Recording #2.wav", "duration": 7.0, "text": "טלפון ארבע שבע תשע שתיים אפס שתיים שתיים אחד תשע תשע "}
...

Each line is a JSON referencing a dataset with its label and duration. I understand that I might need to reorganize the data to be compatible with the train.py, but could you please provide any guidance on how to initiate finetuning the model? Happy to provide additional information if needed.

**Comment by imvladikon** [comment]
Hi @BenRachmiel ,
there are two ways how to do it:
1. put your dataset into the huggingface dataset, like I did it here: https://huggingface.co/datasets/imvladikon/hebrew_speech_coursera   

2. it's possible to load data from csv, in that case need to pass `dataset_path` - it's folder where need to put in csv format "train-all.csv" and "eval-all.csv" where will be two columns - filepath and text (which is our label) - it's possible to check code here: https://github.com/imvladikon/wav2vec2-hebrew/blob/main/train/run_train.py#L614

for both ways need to provide (if needed) `audio_column_name` and `text_column_name` like it was done by me here https://github.com/imvladikon/wav2vec2-hebrew/blob/main/train/run_distributed_train.sh#L6
in your case `audio_column_name=audio_filepath` and `text_column_name=text`

**Comment by BenRachmiel** [comment]
Oh amazing, I didn't look at that file. Apologies. I'll get on that and if things work out well, post an update with how the training goes. I've got about 650,000 audio recordings to train on so it might be a bit. Thanks a ton!

**Comment by imvladikon** [comment]
you're welcome!
`post an update with how the training goes`
Sure, it will be interesting!
